-- 262 · POLÍTICAS POR ACCIÓN — columnas de acción, siembra, procesos nuevos y modo.
--
-- GENERADO desde lib/politicas-modulos.ts por scripts/generar_262_permisos_acciones.mts.
-- NO EDITAR A MANO: cambia el catálogo y regenera (la prueba tests/politicas-modulos.test.ts
-- falla si este archivo y el catálogo no coinciden).
--
-- QUÉ HACE
--   A. Por cada (módulo, verbo) silencioso del catálogo, una columna booleana
--      "<llave>__<verbo>" en public.permisos_usuarios (default false) y, SOLO AL CREARLA,
--      la siembra: acción = true para quien tiene el módulo. Así nadie pierde nada el día uno.
--      Volver a correr el script no re-otorga lo que un administrador ya quitó.
--   B. Los 16 procesos con clave nuevos en public.autorizacion_procesos (grupos Órdenes,
--      Inventario, Facturación, Nómina, Seguridad).
--   C. El modo de las puertas: public.autorizacion_config('politicas_acciones_modo') = 'aviso'.
--      En 'aviso', módulo sí / acción no deja rastro en autorizacion_log y pasa. Cuando el
--      log lleve días en cero: update … set valor = 'bloquear'. Sin desplegar.
--   D. Perfiles: cada perfil que enciende un módulo enciende también sus acciones, y cada
--      perfil que enciende el módulo de un proceso nuevo recibe ese proceso. Quien hoy hace
--      la acción sin clave (porque tiene el módulo) no debe quedar sin poder hacerla.
--   E. notify pgrst: PostgREST recarga el esquema para ver las columnas nuevas.
--
-- Columnas: 318 (sobre 130 llaves de módulo). Verificación: scripts/263_verificar_262_permisos_acciones.sql.
-- Reversa: no hace falta borrar columnas; con modo 'aviso' las puertas no bloquean. Si hubiera
-- que quitarlas: alter table public.permisos_usuarios drop column "<llave>__<verbo>".

begin;

-- ── A. Columnas de acción + siembra (solo al crear) ──
do $$
declare
  r record;
  creadas int := 0;
  sin_modulo int := 0;
begin
  for r in
    select * from (values
    ('acumulados_lipgo', 'acumulados_lipgo__exportar'),
    ('apoyo_cargue', 'apoyo_cargue__crear'),
    ('apoyo_cargue', 'apoyo_cargue__eliminar'),
    ('aprobacion_produccion', 'aprobacion_produccion__anular'),
    ('aprobacion_produccion', 'aprobacion_produccion__aprobar'),
    ('aprobacionturnos', 'aprobacionturnos__anular'),
    ('aprobacionturnos', 'aprobacionturnos__aprobar'),
    ('asignacion_horas_extra', 'asignacion_horas_extra__aprobar'),
    ('asignacion_lotes', 'asignacion_lotes__crear'),
    ('asistencia_administrativa', 'asistencia_administrativa__cerrar'),
    ('asistencia_administrativa', 'asistencia_administrativa__crear'),
    ('asistencia_administrativa', 'asistencia_administrativa__editar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__crear'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__editar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__eliminar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__exportar'),
    ('auditoria_inventario', 'auditoria_inventario__crear'),
    ('auditoria_inventario', 'auditoria_inventario__editar'),
    ('ausentismos', 'ausentismos__configurar'),
    ('ausentismos', 'ausentismos__crear'),
    ('ausentismos', 'ausentismos__editar'),
    ('ausentismos', 'ausentismos__eliminar'),
    ('bascula', 'bascula__editar'),
    ('bitacora', 'bitacora__crear'),
    ('bitacora', 'bitacora__editar'),
    ('bitacora', 'bitacora__eliminar'),
    ('bitacora_auditoria', 'bitacora_auditoria__exportar'),
    ('bonos', 'bonos__anular'),
    ('bonos', 'bonos__crear'),
    ('bonos', 'bonos__eliminar'),
    ('calificacion_conductor', 'calificacion_conductor__configurar'),
    ('calificacion_conductor', 'calificacion_conductor__crear'),
    ('capacitaciones', 'capacitaciones__crear'),
    ('capacitaciones', 'capacitaciones__editar'),
    ('capacitaciones', 'capacitaciones__eliminar'),
    ('capacitaciones', 'capacitaciones__exportar'),
    ('cargos_fijos', 'cargos_fijos__configurar'),
    ('cargos_fijos', 'cargos_fijos__crear'),
    ('cargos_fijos', 'cargos_fijos__editar'),
    ('centro_coordinacion', 'centro_coordinacion__editar'),
    ('ciclo_facturacion', 'ciclo_facturacion__configurar'),
    ('config_bodegas', 'config_bodegas__crear'),
    ('config_bodegas', 'config_bodegas__editar'),
    ('config_bodegas', 'config_bodegas__eliminar'),
    ('config_bodegas', 'config_bodegas__exportar'),
    ('config_categorias', 'config_categorias__crear'),
    ('config_categorias', 'config_categorias__editar'),
    ('config_categorias', 'config_categorias__eliminar'),
    ('config_categorias', 'config_categorias__exportar'),
    ('config_clientes', 'config_clientes__crear'),
    ('config_clientes', 'config_clientes__editar'),
    ('config_clientes', 'config_clientes__eliminar'),
    ('config_clientes', 'config_clientes__exportar'),
    ('config_condiciones_pago', 'config_condiciones_pago__crear'),
    ('config_condiciones_pago', 'config_condiciones_pago__editar'),
    ('config_condiciones_pago', 'config_condiciones_pago__eliminar'),
    ('config_condiciones_pago', 'config_condiciones_pago__exportar'),
    ('config_destinos', 'config_destinos__crear'),
    ('config_destinos', 'config_destinos__editar'),
    ('config_destinos', 'config_destinos__eliminar'),
    ('config_destinos', 'config_destinos__exportar'),
    ('config_grupos', 'config_grupos__crear'),
    ('config_grupos', 'config_grupos__editar'),
    ('config_grupos', 'config_grupos__eliminar'),
    ('config_grupos', 'config_grupos__exportar'),
    ('config_localizaciones', 'config_localizaciones__crear'),
    ('config_localizaciones', 'config_localizaciones__editar'),
    ('config_localizaciones', 'config_localizaciones__eliminar'),
    ('config_localizaciones', 'config_localizaciones__exportar'),
    ('config_medios', 'config_medios__crear'),
    ('config_medios', 'config_medios__editar'),
    ('config_medios', 'config_medios__eliminar'),
    ('config_medios', 'config_medios__exportar'),
    ('config_productos', 'config_productos__crear'),
    ('config_productos', 'config_productos__editar'),
    ('config_productos', 'config_productos__eliminar'),
    ('config_productos', 'config_productos__exportar'),
    ('config_subcategorias', 'config_subcategorias__crear'),
    ('config_subcategorias', 'config_subcategorias__editar'),
    ('config_subcategorias', 'config_subcategorias__eliminar'),
    ('config_subcategorias', 'config_subcategorias__exportar'),
    ('config_sucursales', 'config_sucursales__crear'),
    ('config_sucursales', 'config_sucursales__editar'),
    ('config_sucursales', 'config_sucursales__eliminar'),
    ('config_sucursales', 'config_sucursales__exportar'),
    ('config_tipos_despacho', 'config_tipos_despacho__crear'),
    ('config_tipos_despacho', 'config_tipos_despacho__editar'),
    ('config_tipos_despacho', 'config_tipos_despacho__eliminar'),
    ('config_tipos_despacho', 'config_tipos_despacho__exportar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__crear'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__editar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__eliminar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__exportar'),
    ('config_transportadoras', 'config_transportadoras__crear'),
    ('config_transportadoras', 'config_transportadoras__editar'),
    ('config_transportadoras', 'config_transportadoras__eliminar'),
    ('config_transportadoras', 'config_transportadoras__exportar'),
    ('config_vendedores', 'config_vendedores__crear'),
    ('config_vendedores', 'config_vendedores__editar'),
    ('config_vendedores', 'config_vendedores__eliminar'),
    ('config_vendedores', 'config_vendedores__exportar'),
    ('controlpiso', 'controlpiso__editar'),
    ('controlpiso', 'controlpiso__eliminar'),
    ('creacion_materiales', 'creacion_materiales__crear'),
    ('creacion_materiales', 'creacion_materiales__editar'),
    ('creacion_materiales', 'creacion_materiales__eliminar'),
    ('creacion_materiales', 'creacion_materiales__exportar'),
    ('cuadre_inventario', 'cuadre_inventario__configurar'),
    ('cuadre_inventario', 'cuadre_inventario__crear'),
    ('cuadre_inventario', 'cuadre_inventario__editar'),
    ('cuadre_inventario', 'cuadre_inventario__eliminar'),
    ('cuadro_facturacion', 'cuadro_facturacion__crear'),
    ('cuadro_facturacion', 'cuadro_facturacion__eliminar'),
    ('cuadro_facturacion', 'cuadro_facturacion__exportar'),
    ('dashboardrecepcion', 'dashboardrecepcion__exportar'),
    ('distribucion', 'distribucion__crear'),
    ('dotacion_epp', 'dotacion_epp__crear'),
    ('dotacion_epp', 'dotacion_epp__editar'),
    ('dotacion_epp', 'dotacion_epp__eliminar'),
    ('entrada_pedidos', 'entrada_pedidos__crear'),
    ('entrada_pedidos', 'entrada_pedidos__editar'),
    ('estadoresultados', 'estadoresultados__configurar'),
    ('evaluacionpersonal', 'evaluacionpersonal__crear'),
    ('evidenciasido', 'evidenciasido__editar'),
    ('evidenciasinducciones', 'evidenciasinducciones__cerrar'),
    ('evidenciasinducciones', 'evidenciasinducciones__crear'),
    ('evidenciasinducciones', 'evidenciasinducciones__editar'),
    ('evidenciasinducciones', 'evidenciasinducciones__eliminar'),
    ('examenes_medicos', 'examenes_medicos__configurar'),
    ('examenes_medicos', 'examenes_medicos__crear'),
    ('examenes_medicos', 'examenes_medicos__editar'),
    ('examenes_medicos', 'examenes_medicos__eliminar'),
    ('explosion_materiales', 'explosion_materiales__crear'),
    ('explosion_materiales', 'explosion_materiales__editar'),
    ('explosion_materiales', 'explosion_materiales__eliminar'),
    ('facturacion_proyectos', 'facturacion_proyectos__exportar'),
    ('gastos', 'gastos__crear'),
    ('generar_ordenes_cargue', 'generar_ordenes_cargue__crear'),
    ('generar_ordenes_descargue', 'generar_ordenes_descargue__crear'),
    ('gestion_colaboradores', 'gestion_colaboradores__crear'),
    ('gestion_colaboradores', 'gestion_colaboradores__editar'),
    ('gestion_colaboradores', 'gestion_colaboradores__eliminar'),
    ('gestion_contratos', 'gestion_contratos__crear'),
    ('gestion_contratos', 'gestion_contratos__editar'),
    ('gestion_contratos', 'gestion_contratos__eliminar'),
    ('gestion_ordenes', 'gestion_ordenes__editar'),
    ('gestion_ordenes', 'gestion_ordenes__exportar'),
    ('gestion_proveedores', 'gestion_proveedores__crear'),
    ('gestion_proveedores', 'gestion_proveedores__editar'),
    ('gestion_proveedores', 'gestion_proveedores__eliminar'),
    ('gestion_proveedores', 'gestion_proveedores__exportar'),
    ('gestion_transacciones', 'gestion_transacciones__exportar'),
    ('gestion_usuarios', 'gestion_usuarios__configurar'),
    ('gestion_usuarios', 'gestion_usuarios__crear'),
    ('gestion_usuarios', 'gestion_usuarios__editar'),
    ('gestionar_pedidos', 'gestionar_pedidos__editar'),
    ('gestionar_pedidos', 'gestionar_pedidos__eliminar'),
    ('gestionar_pedidos', 'gestionar_pedidos__exportar'),
    ('gestionfacturas', 'gestionfacturas__anular'),
    ('gestionfacturas', 'gestionfacturas__editar'),
    ('gestionfacturas', 'gestionfacturas__exportar'),
    ('gestionsolicitudes', 'gestionsolicitudes__anular'),
    ('gestionsolicitudes', 'gestionsolicitudes__aprobar'),
    ('gestionsolicitudes', 'gestionsolicitudes__crear'),
    ('gestionsolicitudes', 'gestionsolicitudes__editar'),
    ('gestionsolicitudes', 'gestionsolicitudes__eliminar'),
    ('gestionsolicitudes', 'gestionsolicitudes__exportar'),
    ('gh_entrevistas', 'gh_entrevistas__crear'),
    ('gh_entrevistas', 'gh_entrevistas__editar'),
    ('gh_entrevistas', 'gh_entrevistas__eliminar'),
    ('gh_participacion', 'gh_participacion__crear'),
    ('gh_participacion', 'gh_participacion__editar'),
    ('headcount', 'headcount__crear'),
    ('headcount', 'headcount__editar'),
    ('headcount', 'headcount__eliminar'),
    ('historial_aprobaciones', 'historial_aprobaciones__exportar'),
    ('historial_bascula', 'historial_bascula__exportar'),
    ('historial_lotes', 'historial_lotes__anular'),
    ('historial_lotes', 'historial_lotes__exportar'),
    ('inducciones', 'inducciones__cerrar'),
    ('inducciones', 'inducciones__crear'),
    ('inducciones', 'inducciones__editar'),
    ('inducciones', 'inducciones__eliminar'),
    ('ingreso_produccion', 'ingreso_produccion__crear'),
    ('iso_repositorio', 'iso_repositorio__cerrar'),
    ('iso_repositorio', 'iso_repositorio__crear'),
    ('iso_repositorio', 'iso_repositorio__editar'),
    ('iso_repositorio', 'iso_repositorio__eliminar'),
    ('liquidacion_tolva', 'liquidacion_tolva__cerrar'),
    ('liquidaciones', 'liquidaciones__editar'),
    ('montacargas', 'montacargas__crear'),
    ('montacargas', 'montacargas__editar'),
    ('montacargas', 'montacargas__eliminar'),
    ('montacargasdia', 'montacargasdia__crear'),
    ('montacargasdia', 'montacargasdia__editar'),
    ('montacargasdia', 'montacargasdia__eliminar'),
    ('montacargasdia', 'montacargasdia__exportar'),
    ('muelles_empresa', 'muelles_empresa__crear'),
    ('muelles_empresa', 'muelles_empresa__editar'),
    ('muelles_empresa', 'muelles_empresa__eliminar'),
    ('nominapersonal', 'nominapersonal__exportar'),
    ('notificaciones', 'notificaciones__configurar'),
    ('notificaciones', 'notificaciones__crear'),
    ('novedades_personal', 'novedades_personal__crear'),
    ('novedades_personal', 'novedades_personal__editar'),
    ('packing', 'packing__cerrar'),
    ('packing', 'packing__editar'),
    ('packing', 'packing__exportar'),
    ('parafiscales', 'parafiscales__editar'),
    ('parafiscales', 'parafiscales__exportar'),
    ('picking', 'picking__cerrar'),
    ('picking', 'picking__editar'),
    ('picking', 'picking__exportar'),
    ('placas_distribucion', 'placas_distribucion__crear'),
    ('placas_distribucion', 'placas_distribucion__editar'),
    ('placas_distribucion', 'placas_distribucion__eliminar'),
    ('prechequeo', 'prechequeo__crear'),
    ('prechequeo', 'prechequeo__editar'),
    ('prefactura_produccion', 'prefactura_produccion__crear'),
    ('prefactura_produccion', 'prefactura_produccion__eliminar'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__cerrar'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__crear'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__editar'),
    ('programacion_cliente', 'programacion_cliente__editar'),
    ('programacion_cliente_lip', 'programacion_cliente_lip__editar'),
    ('programacionturnos', 'programacionturnos__configurar'),
    ('programacionturnos', 'programacionturnos__crear'),
    ('programacionturnos', 'programacionturnos__eliminar'),
    ('proyecciones', 'proyecciones__editar'),
    ('recobro_incapacidades', 'recobro_incapacidades__editar'),
    ('registrar_vehiculos', 'registrar_vehiculos__crear'),
    ('registro_asistencia', 'registro_asistencia__crear'),
    ('registro_qr_estibas', 'registro_qr_estibas__crear'),
    ('registro_sanitario', 'registro_sanitario__crear'),
    ('reprocesos', 'reprocesos__crear'),
    ('reprocesos', 'reprocesos__eliminar'),
    ('revision_nomina', 'revision_nomina__crear'),
    ('saldos_inventario', 'saldos_inventario__exportar'),
    ('saldos_producto', 'saldos_producto__exportar'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__crear'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__editar'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__eliminar'),
    ('sig_iso14001', 'sig_iso14001__crear'),
    ('sig_iso14001', 'sig_iso14001__editar'),
    ('sig_iso14001', 'sig_iso14001__eliminar'),
    ('sig_matriz', 'sig_matriz__configurar'),
    ('sig_matriz', 'sig_matriz__crear'),
    ('sig_matriz', 'sig_matriz__editar'),
    ('sig_matriz', 'sig_matriz__eliminar'),
    ('siigo_facturas', 'siigo_facturas__configurar'),
    ('solicitud_personal', 'solicitud_personal__crear'),
    ('solicitudturnos', 'solicitudturnos__crear'),
    ('solicitudturnos', 'solicitudturnos__exportar'),
    ('sst_actividades', 'sst_actividades__crear'),
    ('sst_actividades', 'sst_actividades__editar'),
    ('sst_alertas_at', 'sst_alertas_at__crear'),
    ('sst_alertas_at', 'sst_alertas_at__editar'),
    ('sst_auditoria', 'sst_auditoria__cerrar'),
    ('sst_auditoria', 'sst_auditoria__editar'),
    ('sst_autoevaluacion', 'sst_autoevaluacion__cerrar'),
    ('sst_autoevaluacion', 'sst_autoevaluacion__editar'),
    ('sst_comunicacion', 'sst_comunicacion__crear'),
    ('sst_comunicacion', 'sst_comunicacion__editar'),
    ('sst_epp', 'sst_epp__crear'),
    ('sst_epp', 'sst_epp__editar'),
    ('sst_gestion_cambio', 'sst_gestion_cambio__crear'),
    ('sst_gestion_cambio', 'sst_gestion_cambio__editar'),
    ('sst_incidentes', 'sst_incidentes__crear'),
    ('sst_incidentes', 'sst_incidentes__editar'),
    ('sst_indicadores', 'sst_indicadores__cerrar'),
    ('sst_indicadores', 'sst_indicadores__crear'),
    ('sst_indicadores', 'sst_indicadores__editar'),
    ('sst_indicadores', 'sst_indicadores__eliminar'),
    ('sst_investigaciones', 'sst_investigaciones__crear'),
    ('sst_investigaciones', 'sst_investigaciones__editar'),
    ('sst_ipevr', 'sst_ipevr__crear'),
    ('sst_ipevr', 'sst_ipevr__editar'),
    ('sst_mantenimiento', 'sst_mantenimiento__crear'),
    ('sst_mantenimiento', 'sst_mantenimiento__editar'),
    ('sst_medevac', 'sst_medevac__aprobar'),
    ('sst_medevac', 'sst_medevac__crear'),
    ('sst_medevac', 'sst_medevac__editar'),
    ('sst_medevac', 'sst_medevac__eliminar'),
    ('sst_perfil', 'sst_perfil__aprobar'),
    ('sst_perfil', 'sst_perfil__crear'),
    ('sst_perfil', 'sst_perfil__editar'),
    ('sst_perfil', 'sst_perfil__eliminar'),
    ('sst_plan_mejora', 'sst_plan_mejora__cerrar'),
    ('sst_plan_mejora', 'sst_plan_mejora__crear'),
    ('sst_plan_mejora', 'sst_plan_mejora__editar'),
    ('sst_plan_mejora', 'sst_plan_mejora__eliminar'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__anular'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__crear'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__eliminar'),
    ('tabla_asistencia', 'tabla_asistencia__crear'),
    ('tabla_asistencia', 'tabla_asistencia__editar'),
    ('tabla_asistencia', 'tabla_asistencia__eliminar'),
    ('tarifas', 'tarifas__exportar'),
    ('tolva', 'tolva__crear'),
    ('tolva', 'tolva__editar'),
    ('transacciones_inventario', 'transacciones_inventario__crear'),
    ('transacciones_inventario', 'transacciones_inventario__exportar'),
    ('traslados_producto', 'traslados_producto__crear'),
    ('vacaciones', 'vacaciones__anular'),
    ('vacaciones', 'vacaciones__aprobar'),
    ('vacaciones', 'vacaciones__cerrar'),
    ('vacaciones', 'vacaciones__crear'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__crear'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__editar'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__eliminar'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__exportar'),
    ('ver_solicitudes_traslado', 'ver_solicitudes_traslado__crear'),
    ('ver_tolva', 'ver_tolva__editar'),
    ('ver_tolva', 'ver_tolva__eliminar'),
    ('ver_vehiculos', 'ver_vehiculos__cerrar'),
    ('ver_vehiculos', 'ver_vehiculos__editar'),
    ('ver_vehiculos', 'ver_vehiculos__eliminar'),
    ('ver_vehiculos', 'ver_vehiculos__exportar')
    ) as v(llave, accion)
  loop
    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'permisos_usuarios' and column_name = r.accion
    ) then
      continue;
    end if;
    execute format('alter table public.permisos_usuarios add column %I boolean not null default false', r.accion);
    creadas := creadas + 1;
    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'permisos_usuarios' and column_name = r.llave
    ) then
      execute format('update public.permisos_usuarios set %I = true where %I is true', r.accion, r.llave);
    else
      sin_modulo := sin_modulo + 1;
      raise warning 'la llave de módulo % no existe como columna: % se creó sin sembrar', r.llave, r.accion;
    end if;
  end loop;
  raise notice 'columnas de acción creadas y sembradas: % (sin módulo: %)', creadas, sin_modulo;
end $$;

-- ── B. Procesos con clave nuevos ──
insert into public.autorizacion_procesos (codigo, nombre, descripcion, grupo, orden, con_alcance) values
  ('ord_eliminar', 'Eliminar orden de cargue / descargue', 'Gestión de Ordenes › Eliminar. Revierte inventario (invtrans), aprobaciones de calidad y pedidos asociados: irreversible.', 'Órdenes', 10, true),
  ('bas_corregir', 'Corregir un pesaje de báscula', 'Historial Báscula › Editar. Reemplaza la clave fija que vivía en el navegador.', 'Órdenes', 20, true),
  ('inv_cierre_mes', 'Cerrar el mes de inventario', 'Panel LIP Inventario / Auditoría de Inventario › Cierre mensual.', 'Inventario', 200, true),
  ('inv_acta_firmar', 'Firmar el acta de inventario', 'Auditoría de Inventario › Firmar acta del cliente.', 'Inventario', 210, true),
  ('inv_cuadre_cerrar_mes', 'Cerrar el mes del cuadre (contabiliza correcciones)', 'Cuadre de Inventario › Cierre mensual: postea todas las correcciones a invtrans y mueve el stock.', 'Inventario', 220, true),
  ('fac_prefactura_aprobar', 'Aprobar o reabrir una prefactura', 'Cuadro de Control Facturación › Aprobar / Reabrir.', 'Facturación', 10, true),
  ('fac_registrar_pago', 'Registrar un pago de contado', 'Ciclo de Facturación › Pagos de Contado › Registrar pago.', 'Facturación', 20, true),
  ('fac_emitir_siigo', 'Emitir factura en Siigo (DIAN)', 'Ciclo de Facturación › Facturar en Siigo. Si la emisión va a la DIAN es irreversible: solo se anula con nota crédito.', 'Facturación', 30, true),
  ('fac_prefactura_prod_aprobar', 'Aprobar prefactura de producción', 'Prefactura de Producción › Aprobar.', 'Facturación', 40, true),
  ('fac_corregir_orden', 'Corregir una orden ya facturada', 'Corrección de Órdenes › Guardar corrección.', 'Facturación', 50, true),
  ('fac_tarifas', 'Cambiar tarifas', 'Tarifas › crear, editar o eliminar una tarifa (también desde LIPbot).', 'Facturación', 60, true),
  ('nom_ajustes_aprobar', 'Aprobar o rechazar ajustes de nómina', 'Revisión de nómina › Aprobar / Rechazar.', 'Nómina', 10, false),
  ('nom_liquidacion_aprobar', 'Aprobar una liquidación', 'Liquidaciones › Aprobar.', 'Nómina', 20, false),
  ('nom_parametros', 'Cambiar parámetros de liquidación y pago', 'Liquidaciones, Parafiscales, Turnos y tarifas por puesto, políticas de horas extra.', 'Nómina', 30, false),
  ('nom_periodo_pagar', 'Marcar un período como pagado', 'Parafiscales › Período pagado.', 'Nómina', 40, false),
  ('seg_usuario_eliminar', 'Eliminar un usuario', 'Gestión de Usuarios › Eliminar usuario (borra la cuenta de acceso).', 'Seguridad', 10, false)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      grupo = excluded.grupo,
      orden = excluded.orden,
      con_alcance = excluded.con_alcance;

-- ── C. Modo de las puertas: nace en 'aviso' ──
insert into public.autorizacion_config (clave, valor)
values ('politicas_acciones_modo', 'aviso')
on conflict (clave) do nothing;

-- ── D. Perfiles: acciones de los módulos que ya encienden, y procesos nuevos ──
do $$
declare
  r record;
  filas int;
  n_acc int := 0;
  n_pro int := 0;
begin
  for r in
    select * from (values
    ('acumulados_lipgo', 'acumulados_lipgo__exportar'),
    ('apoyo_cargue', 'apoyo_cargue__crear'),
    ('apoyo_cargue', 'apoyo_cargue__eliminar'),
    ('aprobacion_produccion', 'aprobacion_produccion__anular'),
    ('aprobacion_produccion', 'aprobacion_produccion__aprobar'),
    ('aprobacionturnos', 'aprobacionturnos__anular'),
    ('aprobacionturnos', 'aprobacionturnos__aprobar'),
    ('asignacion_horas_extra', 'asignacion_horas_extra__aprobar'),
    ('asignacion_lotes', 'asignacion_lotes__crear'),
    ('asistencia_administrativa', 'asistencia_administrativa__cerrar'),
    ('asistencia_administrativa', 'asistencia_administrativa__crear'),
    ('asistencia_administrativa', 'asistencia_administrativa__editar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__crear'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__editar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__eliminar'),
    ('asistencia_capacitaciones', 'asistencia_capacitaciones__exportar'),
    ('auditoria_inventario', 'auditoria_inventario__crear'),
    ('auditoria_inventario', 'auditoria_inventario__editar'),
    ('ausentismos', 'ausentismos__configurar'),
    ('ausentismos', 'ausentismos__crear'),
    ('ausentismos', 'ausentismos__editar'),
    ('ausentismos', 'ausentismos__eliminar'),
    ('bascula', 'bascula__editar'),
    ('bitacora', 'bitacora__crear'),
    ('bitacora', 'bitacora__editar'),
    ('bitacora', 'bitacora__eliminar'),
    ('bitacora_auditoria', 'bitacora_auditoria__exportar'),
    ('bonos', 'bonos__anular'),
    ('bonos', 'bonos__crear'),
    ('bonos', 'bonos__eliminar'),
    ('calificacion_conductor', 'calificacion_conductor__configurar'),
    ('calificacion_conductor', 'calificacion_conductor__crear'),
    ('capacitaciones', 'capacitaciones__crear'),
    ('capacitaciones', 'capacitaciones__editar'),
    ('capacitaciones', 'capacitaciones__eliminar'),
    ('capacitaciones', 'capacitaciones__exportar'),
    ('cargos_fijos', 'cargos_fijos__configurar'),
    ('cargos_fijos', 'cargos_fijos__crear'),
    ('cargos_fijos', 'cargos_fijos__editar'),
    ('centro_coordinacion', 'centro_coordinacion__editar'),
    ('ciclo_facturacion', 'ciclo_facturacion__configurar'),
    ('config_bodegas', 'config_bodegas__crear'),
    ('config_bodegas', 'config_bodegas__editar'),
    ('config_bodegas', 'config_bodegas__eliminar'),
    ('config_bodegas', 'config_bodegas__exportar'),
    ('config_categorias', 'config_categorias__crear'),
    ('config_categorias', 'config_categorias__editar'),
    ('config_categorias', 'config_categorias__eliminar'),
    ('config_categorias', 'config_categorias__exportar'),
    ('config_clientes', 'config_clientes__crear'),
    ('config_clientes', 'config_clientes__editar'),
    ('config_clientes', 'config_clientes__eliminar'),
    ('config_clientes', 'config_clientes__exportar'),
    ('config_condiciones_pago', 'config_condiciones_pago__crear'),
    ('config_condiciones_pago', 'config_condiciones_pago__editar'),
    ('config_condiciones_pago', 'config_condiciones_pago__eliminar'),
    ('config_condiciones_pago', 'config_condiciones_pago__exportar'),
    ('config_destinos', 'config_destinos__crear'),
    ('config_destinos', 'config_destinos__editar'),
    ('config_destinos', 'config_destinos__eliminar'),
    ('config_destinos', 'config_destinos__exportar'),
    ('config_grupos', 'config_grupos__crear'),
    ('config_grupos', 'config_grupos__editar'),
    ('config_grupos', 'config_grupos__eliminar'),
    ('config_grupos', 'config_grupos__exportar'),
    ('config_localizaciones', 'config_localizaciones__crear'),
    ('config_localizaciones', 'config_localizaciones__editar'),
    ('config_localizaciones', 'config_localizaciones__eliminar'),
    ('config_localizaciones', 'config_localizaciones__exportar'),
    ('config_medios', 'config_medios__crear'),
    ('config_medios', 'config_medios__editar'),
    ('config_medios', 'config_medios__eliminar'),
    ('config_medios', 'config_medios__exportar'),
    ('config_productos', 'config_productos__crear'),
    ('config_productos', 'config_productos__editar'),
    ('config_productos', 'config_productos__eliminar'),
    ('config_productos', 'config_productos__exportar'),
    ('config_subcategorias', 'config_subcategorias__crear'),
    ('config_subcategorias', 'config_subcategorias__editar'),
    ('config_subcategorias', 'config_subcategorias__eliminar'),
    ('config_subcategorias', 'config_subcategorias__exportar'),
    ('config_sucursales', 'config_sucursales__crear'),
    ('config_sucursales', 'config_sucursales__editar'),
    ('config_sucursales', 'config_sucursales__eliminar'),
    ('config_sucursales', 'config_sucursales__exportar'),
    ('config_tipos_despacho', 'config_tipos_despacho__crear'),
    ('config_tipos_despacho', 'config_tipos_despacho__editar'),
    ('config_tipos_despacho', 'config_tipos_despacho__eliminar'),
    ('config_tipos_despacho', 'config_tipos_despacho__exportar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__crear'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__editar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__eliminar'),
    ('config_tipos_vehiculos', 'config_tipos_vehiculos__exportar'),
    ('config_transportadoras', 'config_transportadoras__crear'),
    ('config_transportadoras', 'config_transportadoras__editar'),
    ('config_transportadoras', 'config_transportadoras__eliminar'),
    ('config_transportadoras', 'config_transportadoras__exportar'),
    ('config_vendedores', 'config_vendedores__crear'),
    ('config_vendedores', 'config_vendedores__editar'),
    ('config_vendedores', 'config_vendedores__eliminar'),
    ('config_vendedores', 'config_vendedores__exportar'),
    ('controlpiso', 'controlpiso__editar'),
    ('controlpiso', 'controlpiso__eliminar'),
    ('creacion_materiales', 'creacion_materiales__crear'),
    ('creacion_materiales', 'creacion_materiales__editar'),
    ('creacion_materiales', 'creacion_materiales__eliminar'),
    ('creacion_materiales', 'creacion_materiales__exportar'),
    ('cuadre_inventario', 'cuadre_inventario__configurar'),
    ('cuadre_inventario', 'cuadre_inventario__crear'),
    ('cuadre_inventario', 'cuadre_inventario__editar'),
    ('cuadre_inventario', 'cuadre_inventario__eliminar'),
    ('cuadro_facturacion', 'cuadro_facturacion__crear'),
    ('cuadro_facturacion', 'cuadro_facturacion__eliminar'),
    ('cuadro_facturacion', 'cuadro_facturacion__exportar'),
    ('dashboardrecepcion', 'dashboardrecepcion__exportar'),
    ('distribucion', 'distribucion__crear'),
    ('dotacion_epp', 'dotacion_epp__crear'),
    ('dotacion_epp', 'dotacion_epp__editar'),
    ('dotacion_epp', 'dotacion_epp__eliminar'),
    ('entrada_pedidos', 'entrada_pedidos__crear'),
    ('entrada_pedidos', 'entrada_pedidos__editar'),
    ('estadoresultados', 'estadoresultados__configurar'),
    ('evaluacionpersonal', 'evaluacionpersonal__crear'),
    ('evidenciasido', 'evidenciasido__editar'),
    ('evidenciasinducciones', 'evidenciasinducciones__cerrar'),
    ('evidenciasinducciones', 'evidenciasinducciones__crear'),
    ('evidenciasinducciones', 'evidenciasinducciones__editar'),
    ('evidenciasinducciones', 'evidenciasinducciones__eliminar'),
    ('examenes_medicos', 'examenes_medicos__configurar'),
    ('examenes_medicos', 'examenes_medicos__crear'),
    ('examenes_medicos', 'examenes_medicos__editar'),
    ('examenes_medicos', 'examenes_medicos__eliminar'),
    ('explosion_materiales', 'explosion_materiales__crear'),
    ('explosion_materiales', 'explosion_materiales__editar'),
    ('explosion_materiales', 'explosion_materiales__eliminar'),
    ('facturacion_proyectos', 'facturacion_proyectos__exportar'),
    ('gastos', 'gastos__crear'),
    ('generar_ordenes_cargue', 'generar_ordenes_cargue__crear'),
    ('generar_ordenes_descargue', 'generar_ordenes_descargue__crear'),
    ('gestion_colaboradores', 'gestion_colaboradores__crear'),
    ('gestion_colaboradores', 'gestion_colaboradores__editar'),
    ('gestion_colaboradores', 'gestion_colaboradores__eliminar'),
    ('gestion_contratos', 'gestion_contratos__crear'),
    ('gestion_contratos', 'gestion_contratos__editar'),
    ('gestion_contratos', 'gestion_contratos__eliminar'),
    ('gestion_ordenes', 'gestion_ordenes__editar'),
    ('gestion_ordenes', 'gestion_ordenes__exportar'),
    ('gestion_proveedores', 'gestion_proveedores__crear'),
    ('gestion_proveedores', 'gestion_proveedores__editar'),
    ('gestion_proveedores', 'gestion_proveedores__eliminar'),
    ('gestion_proveedores', 'gestion_proveedores__exportar'),
    ('gestion_transacciones', 'gestion_transacciones__exportar'),
    ('gestion_usuarios', 'gestion_usuarios__configurar'),
    ('gestion_usuarios', 'gestion_usuarios__crear'),
    ('gestion_usuarios', 'gestion_usuarios__editar'),
    ('gestionar_pedidos', 'gestionar_pedidos__editar'),
    ('gestionar_pedidos', 'gestionar_pedidos__eliminar'),
    ('gestionar_pedidos', 'gestionar_pedidos__exportar'),
    ('gestionfacturas', 'gestionfacturas__anular'),
    ('gestionfacturas', 'gestionfacturas__editar'),
    ('gestionfacturas', 'gestionfacturas__exportar'),
    ('gestionsolicitudes', 'gestionsolicitudes__anular'),
    ('gestionsolicitudes', 'gestionsolicitudes__aprobar'),
    ('gestionsolicitudes', 'gestionsolicitudes__crear'),
    ('gestionsolicitudes', 'gestionsolicitudes__editar'),
    ('gestionsolicitudes', 'gestionsolicitudes__eliminar'),
    ('gestionsolicitudes', 'gestionsolicitudes__exportar'),
    ('gh_entrevistas', 'gh_entrevistas__crear'),
    ('gh_entrevistas', 'gh_entrevistas__editar'),
    ('gh_entrevistas', 'gh_entrevistas__eliminar'),
    ('gh_participacion', 'gh_participacion__crear'),
    ('gh_participacion', 'gh_participacion__editar'),
    ('headcount', 'headcount__crear'),
    ('headcount', 'headcount__editar'),
    ('headcount', 'headcount__eliminar'),
    ('historial_aprobaciones', 'historial_aprobaciones__exportar'),
    ('historial_bascula', 'historial_bascula__exportar'),
    ('historial_lotes', 'historial_lotes__anular'),
    ('historial_lotes', 'historial_lotes__exportar'),
    ('inducciones', 'inducciones__cerrar'),
    ('inducciones', 'inducciones__crear'),
    ('inducciones', 'inducciones__editar'),
    ('inducciones', 'inducciones__eliminar'),
    ('ingreso_produccion', 'ingreso_produccion__crear'),
    ('iso_repositorio', 'iso_repositorio__cerrar'),
    ('iso_repositorio', 'iso_repositorio__crear'),
    ('iso_repositorio', 'iso_repositorio__editar'),
    ('iso_repositorio', 'iso_repositorio__eliminar'),
    ('liquidacion_tolva', 'liquidacion_tolva__cerrar'),
    ('liquidaciones', 'liquidaciones__editar'),
    ('montacargas', 'montacargas__crear'),
    ('montacargas', 'montacargas__editar'),
    ('montacargas', 'montacargas__eliminar'),
    ('montacargasdia', 'montacargasdia__crear'),
    ('montacargasdia', 'montacargasdia__editar'),
    ('montacargasdia', 'montacargasdia__eliminar'),
    ('montacargasdia', 'montacargasdia__exportar'),
    ('muelles_empresa', 'muelles_empresa__crear'),
    ('muelles_empresa', 'muelles_empresa__editar'),
    ('muelles_empresa', 'muelles_empresa__eliminar'),
    ('nominapersonal', 'nominapersonal__exportar'),
    ('notificaciones', 'notificaciones__configurar'),
    ('notificaciones', 'notificaciones__crear'),
    ('novedades_personal', 'novedades_personal__crear'),
    ('novedades_personal', 'novedades_personal__editar'),
    ('packing', 'packing__cerrar'),
    ('packing', 'packing__editar'),
    ('packing', 'packing__exportar'),
    ('parafiscales', 'parafiscales__editar'),
    ('parafiscales', 'parafiscales__exportar'),
    ('picking', 'picking__cerrar'),
    ('picking', 'picking__editar'),
    ('picking', 'picking__exportar'),
    ('placas_distribucion', 'placas_distribucion__crear'),
    ('placas_distribucion', 'placas_distribucion__editar'),
    ('placas_distribucion', 'placas_distribucion__eliminar'),
    ('prechequeo', 'prechequeo__crear'),
    ('prechequeo', 'prechequeo__editar'),
    ('prefactura_produccion', 'prefactura_produccion__crear'),
    ('prefactura_produccion', 'prefactura_produccion__eliminar'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__cerrar'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__crear'),
    ('procesos_disciplinarios', 'procesos_disciplinarios__editar'),
    ('programacion_cliente', 'programacion_cliente__editar'),
    ('programacion_cliente_lip', 'programacion_cliente_lip__editar'),
    ('programacionturnos', 'programacionturnos__configurar'),
    ('programacionturnos', 'programacionturnos__crear'),
    ('programacionturnos', 'programacionturnos__eliminar'),
    ('proyecciones', 'proyecciones__editar'),
    ('recobro_incapacidades', 'recobro_incapacidades__editar'),
    ('registrar_vehiculos', 'registrar_vehiculos__crear'),
    ('registro_asistencia', 'registro_asistencia__crear'),
    ('registro_qr_estibas', 'registro_qr_estibas__crear'),
    ('registro_sanitario', 'registro_sanitario__crear'),
    ('reprocesos', 'reprocesos__crear'),
    ('reprocesos', 'reprocesos__eliminar'),
    ('revision_nomina', 'revision_nomina__crear'),
    ('saldos_inventario', 'saldos_inventario__exportar'),
    ('saldos_producto', 'saldos_producto__exportar'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__crear'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__editar'),
    ('satisfaccion_pqrsf', 'satisfaccion_pqrsf__eliminar'),
    ('sig_iso14001', 'sig_iso14001__crear'),
    ('sig_iso14001', 'sig_iso14001__editar'),
    ('sig_iso14001', 'sig_iso14001__eliminar'),
    ('sig_matriz', 'sig_matriz__configurar'),
    ('sig_matriz', 'sig_matriz__crear'),
    ('sig_matriz', 'sig_matriz__editar'),
    ('sig_matriz', 'sig_matriz__eliminar'),
    ('siigo_facturas', 'siigo_facturas__configurar'),
    ('solicitud_personal', 'solicitud_personal__crear'),
    ('solicitudturnos', 'solicitudturnos__crear'),
    ('solicitudturnos', 'solicitudturnos__exportar'),
    ('sst_actividades', 'sst_actividades__crear'),
    ('sst_actividades', 'sst_actividades__editar'),
    ('sst_alertas_at', 'sst_alertas_at__crear'),
    ('sst_alertas_at', 'sst_alertas_at__editar'),
    ('sst_auditoria', 'sst_auditoria__cerrar'),
    ('sst_auditoria', 'sst_auditoria__editar'),
    ('sst_autoevaluacion', 'sst_autoevaluacion__cerrar'),
    ('sst_autoevaluacion', 'sst_autoevaluacion__editar'),
    ('sst_comunicacion', 'sst_comunicacion__crear'),
    ('sst_comunicacion', 'sst_comunicacion__editar'),
    ('sst_epp', 'sst_epp__crear'),
    ('sst_epp', 'sst_epp__editar'),
    ('sst_gestion_cambio', 'sst_gestion_cambio__crear'),
    ('sst_gestion_cambio', 'sst_gestion_cambio__editar'),
    ('sst_incidentes', 'sst_incidentes__crear'),
    ('sst_incidentes', 'sst_incidentes__editar'),
    ('sst_indicadores', 'sst_indicadores__cerrar'),
    ('sst_indicadores', 'sst_indicadores__crear'),
    ('sst_indicadores', 'sst_indicadores__editar'),
    ('sst_indicadores', 'sst_indicadores__eliminar'),
    ('sst_investigaciones', 'sst_investigaciones__crear'),
    ('sst_investigaciones', 'sst_investigaciones__editar'),
    ('sst_ipevr', 'sst_ipevr__crear'),
    ('sst_ipevr', 'sst_ipevr__editar'),
    ('sst_mantenimiento', 'sst_mantenimiento__crear'),
    ('sst_mantenimiento', 'sst_mantenimiento__editar'),
    ('sst_medevac', 'sst_medevac__aprobar'),
    ('sst_medevac', 'sst_medevac__crear'),
    ('sst_medevac', 'sst_medevac__editar'),
    ('sst_medevac', 'sst_medevac__eliminar'),
    ('sst_perfil', 'sst_perfil__aprobar'),
    ('sst_perfil', 'sst_perfil__crear'),
    ('sst_perfil', 'sst_perfil__editar'),
    ('sst_perfil', 'sst_perfil__eliminar'),
    ('sst_plan_mejora', 'sst_plan_mejora__cerrar'),
    ('sst_plan_mejora', 'sst_plan_mejora__crear'),
    ('sst_plan_mejora', 'sst_plan_mejora__editar'),
    ('sst_plan_mejora', 'sst_plan_mejora__eliminar'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__anular'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__crear'),
    ('sst_repositorio_soportes', 'sst_repositorio_soportes__eliminar'),
    ('tabla_asistencia', 'tabla_asistencia__crear'),
    ('tabla_asistencia', 'tabla_asistencia__editar'),
    ('tabla_asistencia', 'tabla_asistencia__eliminar'),
    ('tarifas', 'tarifas__exportar'),
    ('tolva', 'tolva__crear'),
    ('tolva', 'tolva__editar'),
    ('transacciones_inventario', 'transacciones_inventario__crear'),
    ('transacciones_inventario', 'transacciones_inventario__exportar'),
    ('traslados_producto', 'traslados_producto__crear'),
    ('vacaciones', 'vacaciones__anular'),
    ('vacaciones', 'vacaciones__aprobar'),
    ('vacaciones', 'vacaciones__cerrar'),
    ('vacaciones', 'vacaciones__crear'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__crear'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__editar'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__eliminar'),
    ('ver_ingresos_produccion', 'ver_ingresos_produccion__exportar'),
    ('ver_solicitudes_traslado', 'ver_solicitudes_traslado__crear'),
    ('ver_tolva', 'ver_tolva__editar'),
    ('ver_tolva', 'ver_tolva__eliminar'),
    ('ver_vehiculos', 'ver_vehiculos__cerrar'),
    ('ver_vehiculos', 'ver_vehiculos__editar'),
    ('ver_vehiculos', 'ver_vehiculos__eliminar'),
    ('ver_vehiculos', 'ver_vehiculos__exportar')
    ) as v(llave, accion)
  loop
    insert into public.acceso_perfil_permisos (perfil_id, permiso)
    select p.perfil_id, r.accion
    from public.acceso_perfil_permisos p
    where p.permiso = r.llave
      and not exists (select 1 from public.acceso_perfil_permisos q where q.perfil_id = p.perfil_id and q.permiso = r.accion);
    get diagnostics filas = row_count;
    n_acc := n_acc + filas;
  end loop;

  for r in
    select * from (values
    ('ord_eliminar', 'gestion_ordenes'),
    ('bas_corregir', 'historial_bascula'),
    ('inv_cierre_mes', 'auditoria_inventario'),
    ('inv_acta_firmar', 'auditoria_inventario'),
    ('inv_cuadre_cerrar_mes', 'cuadre_inventario'),
    ('fac_prefactura_aprobar', 'cuadro_facturacion'),
    ('fac_registrar_pago', 'ciclo_facturacion'),
    ('fac_emitir_siigo', 'ciclo_facturacion'),
    ('fac_prefactura_prod_aprobar', 'prefactura_produccion'),
    ('fac_corregir_orden', 'correccion_ordenes'),
    ('fac_tarifas', 'tarifas'),
    ('nom_ajustes_aprobar', 'revision_nomina'),
    ('nom_liquidacion_aprobar', 'liquidaciones'),
    ('nom_parametros', 'gestionturnos'),
    ('nom_parametros', 'liquidaciones'),
    ('nom_parametros', 'parafiscales'),
    ('nom_parametros', 'tabla_asistencia'),
    ('nom_periodo_pagar', 'parafiscales'),
    ('seg_usuario_eliminar', 'gestion_usuarios')
    ) as v(proceso, llave)
  loop
    insert into public.autorizacion_perfil_procesos (perfil_id, proceso)
    select p.perfil_id, r.proceso
    from public.acceso_perfil_permisos p
    where p.permiso = r.llave
      and not exists (select 1 from public.autorizacion_perfil_procesos q where q.perfil_id = p.perfil_id and q.proceso = r.proceso);
    get diagnostics filas = row_count;
    n_pro := n_pro + filas;
  end loop;
  raise notice 'perfiles: acciones agregadas %, procesos agregados %', n_acc, n_pro;
end $$;

-- ── E. Que PostgREST vea las columnas nuevas ──
notify pgrst, 'reload schema';

commit;

-- ── Verificación rápida (solo lecturas) ──
select count(*) as columnas_de_accion
from information_schema.columns
where table_schema = 'public' and table_name = 'permisos_usuarios' and column_name like '%\_\_%';

select grupo, count(*) as procesos
from public.autorizacion_procesos
where grupo in ('Órdenes', 'Inventario', 'Facturación', 'Nómina', 'Seguridad')
group by grupo order by grupo;

select clave, valor from public.autorizacion_config where clave = 'politicas_acciones_modo';
